# -*- coding: utf-8 -*-
"""Data Standardization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pSL0dzVflwLdMF429r3-QAlhJpmYNmjt

**1: Libaries Import**
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

"""**2: Breast Cancer dataset load**"""

dataset = sklearn.datasets.load_breast_cancer()

print(dataset)

"""**3: Loading data to the pandas dataframe**"""

df = pd.DataFrame(dataset.data, columns= dataset.feature_names)

"""**4: Head and Tail**
▶ **Head** Showing rows in **ascending order**..
▶ **Tail** Showing rows in **descending order**...
"""

df.head(5)

df.tail(5)

"""**5: Shape showing how many rows and columns in your dataframe**"""

df.shape

"""**6: X is a data frame and the Y is the target value or label value so the values are either 0 or 1**"""

X =df
Y = dataset.target

print(X)
print(Y)

"""**7: Specified the range of training data and test data**"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=3)

print(X.shape, X_train.shape, X_test.shape)

"""**8: Standardize the data**"""

print(dataset.data.std())

"""**9: We standardize the data by using standard scalar library**"""

scaler = StandardScaler()

scaler.fit(X_train)

X_train_standardized = scaler.transform(X_train)

print(X_train_standardized)

X_test_standardized = scaler.transform(X_test)

print(X_train_standardized.std())